ProDjango/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls),),
    url(r'^tinymce/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.TINY_MCE_ROOT}),
    url(r'weblog/', include('coltrane.urls', namespace='weblog', app_name='coltrane')),
    url(r'comments/', include('django_comments.urls')),
    url(r'^search/$', 'search.views.search'),
]

coltrane/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views import generic
from .models import Category, Entry, Link
from .views import category_detail


entry_info_year_dict = {
    'date_field': 'pub_date',
    'queryset': Entry.objects.all(),
}

entry_info_dict = {
    'date_field': 'pub_date',
    'queryset': Entry.objects.all(),
    'month_format': '%m',
}

link_info_dict = {
    'date_field': 'pub_date',
    'queryset': Link.objects.all(),
    'month_format': '%m',
}

urlpatterns = [

    # For Categories
    url(r'categories/$', generic.ListView.as_view(
        queryset=Category.objects.all(),
        allow_empty=True,
    ), name='category_list'),

    url(r'categories/(?P<slug>[-_\w]+)/$', category_detail, name='category_detail'),

    # For entry
    url(r'^$', generic.ArchiveIndexView.as_view(
        queryset=Entry.objects.all(),
        date_field='pub_date',
        allow_empty=True),
        name='entry_archive_index'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
        generic.YearArchiveView.as_view(**entry_info_year_dict),
        name='entry_archive_year'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
        generic.MonthArchiveView.as_view(**entry_info_dict),
        name='entry_archive_month'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        generic.DateDetailView.as_view(**entry_info_dict), name='entry_detail'),

    # For links
    url(r'^links/$', generic.ArchiveIndexView.as_view(
        queryset=Link.objects.all(),
        date_field='pub_date',
        allow_empty=True),
        name='link_list'),
    url(r'^links/(?P<year>\d{4})/(?P<month>\d{2})/$',
        generic.MonthArchiveView.as_view(**link_info_dict)),
    url(r'^links/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        generic.DateDetailView.as_view(**link_info_dict), name='link_detail'),
]

templates/base/base_coltrane.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Weblog {% block title %}{% endblock %}</title>
</head>
<body class="{% block bdoyclass %}{% endblock %}">
<div id="header">
    <h1 id="branding">My weblog</h1>
</div>
<div id="content"></div>
    {% block content %}
    {% endblock %}
<div id="sidebar">
    <h2>Navigation</h2>
    <ul id="main-nav">
        <li id="main-nav-entries">
            <a href="{% url 'weblog:entry_archive_index'   %}">Entries</a>
        </li>
        <li id="main-nav-links">
            <a href="{% url 'weblog:link_list' %}">Links</a>
        </li>
{#        <li id="main-nav-categories">#}
{#            <a href="{% url weblog:entry_detailcategory_list %}">Catrgories</a>#}
{#        </li>#}
{#        <li id="main-nav-tags">#}
{#            <a href="{% url weblog:entry_detailtags_list %}">Tags</a>#}
{#        </li>#}
    </ul>
    <h2>What is this?</h2>
    {% block whatis %}
    {% endblock %}

    {% load weblog_tags %}
    <h2>Latest entries in the weblog</h2>
    <ul>
        {% get_latest_content coltrane.entry 5 as latest_entries %}
        {% for entry in latest_entries %}
        <li>
            <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>,
            posted {{ entry.pub_date|timesince }}
        </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

templates/base/entries.html
{% extends "base/base_coltrane.html" %}

{% block title %}| Entries{% endblock %}

{% block bdoyclass %}entries{% endblock %}

templates/base/links.html
{% extends "base/base_coltrane.html" %}

{% block title %}| Links{% endblock %}

{% block bdoyclass %}links{% endblock %}